name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated from v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4  # Updated from v2
        with:
          node-version: '20.9.0'
          cache: 'npm'  # Caches node_modules for faster runs

      - name: Install dependencies
        run: npm ci  # Clean install (faster & more reliable than `npm install`)

      - name: Create production .env
        run: |
          echo "TOPIC_API=${{ secrets.TOPIC_API }}" > .env

      - name: Build
        run: npm run build

      - name: Verify build folder exists
        run: |
          echo "Build folder contents:"
          ls -la build/
          [ -f build/index.html ] || { echo "Error: index.html missing in build folder!"; exit 1; }
          echo "Build verification passed"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: build
          clean: true  # Cleans existing files in gh-pages