name: Merge to Master Pipeline

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  verify-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create production .env
      run: |
        echo "TOPIC_API=${{ secrets.TOPIC_API }}" > .env

    - name: Run tests
      run: npm test